strategy: lstm  # 可选值: 'random', 'ewc', 'lstm', 'timewindow'
num_clients: 5
num_rounds: 10
epochs: 1
lr: 0.01
lstm_config:
  input_size: 5
  hidden_size: 10
  output_size: 1
time_window_config:
  window_size: 10